---

- name: Copy in additional Nagios service plugin
  copy:
    src: plugins/check_service.sh
    dest: /usr/lib64/nagios/plugins/check_service.sh
    owner: root
    group: root
    mode: 0755

- name: Copy nrpe.d OpenShift node configuration files
  copy:
    src: nrpe.d/check_openshift_node.cfg
    dest: /etc/nrpe.d/check_openshift_node.cfg
    owner: root
    group: root
    mode: 0644

