---

- name: Copy in additional Nagios Memory plugins
  copy:
    src: plugins/check_mem
    dest: /usr/lib64/nagios/plugins/check_mem
    owner: root
    group: root
    mode: 0755

- name: Copy nrpe.d Memory configuration files
  copy:
    src: nrpe.d/check_mem.cfg
    dest: /etc/nrpe.d/check_mem.cfg
    owner: root
    group: root
    mode: 0644

