---
- include_tasks: create_atlassian_users.yml
  with_items: "{{ atlassian_users }}"
  loop_control:
    loop_var: atlassian_user
  when: atlassian_users|length > 0

- include_tasks: create_atlassian_groups.yml
  with_items: "{{ atlassian.groups }}"
  loop_control:
    loop_var: group
  when: atlassian.groups|length > 0

- include_tasks: add_user_to_groups.yml
  with_items: "{{ atlassian_users }}"
  loop_control:
    loop_var: atlassian_user
  when: atlassian.user|length > 0

- include_tasks: delete_atlassian_users.yml 
  with_items: "{{ atlassian_users }}"
  loop_control:
    loop_var: atlassian_user
  when: atlassian_delete_users|length > 0

