---

- name: Process all tasks
  include_tasks: process_all_tasks.yml
  loop: "{{ identities.users }}"
  loop_control:
    loop_var: user_data
  loop: "{{ identities.groups }}"
  loop_control:
    loop_var: group_data
  when:
    - identities.targets is undefined or 'rh-sso' in identities.targets
