---

# Ansible Tower Download and Version Information
ansible_tower_download_url: "https://releases.ansible.com/ansible-tower/setup_openshift/ansible-tower-openshift-setup-{{ ansible_tower_version }}.tar.gz"
ansible_tower_version: 3.8.1-1
ansible_tower_remote_src: true

# Initial Default Ansible Tower Config
admin_user: 'admin'
admin_password: 'admin'
admin_email: 'root@localhost'
secret_key: 'abcdefghijkx'

# Default PostgreSQL setup
pg_username: 'pgu'
pg_password: 'pgu'
pg_database: 'tower'
pg_port: '5432'
pg_sslmode: 'prefer'  # set to 'verify-full' for client-side enforced SSL
postgress_activate_wait: "120"

# OpenShift Specific Credentials
openshift_host: "https://api.crc.testing:6443"
openshift_user: "test" # Installer needs a username even when installing with token - using a "fake" value works
openshift_password: ""
openshift_token: ""
openshift_skip_tls_verify: "false"
openshift_project: "tower"

# Postgre can be deployed backed up by either EmptyDir or PVC, PVC will be created if openshift_pg_emptydir is set to false
openshift_pg_emptydir: "true"

# Only applicable if openshift_pg_emptydir is set to "false"
openshift_pg_pvc_size: "10Gi"
openshift_pg_pvc_name: "postgresql"

