---
- name: Create Jira Project
  uri:
    url: "{{ atlassian.jira.url }}/rest/api/2/project"
    method: POST
    user: "{{ atlassian.jira.username }}"
    password: "{{ atlassian.jira.password }}"
    return_content: yes
    force_basic_auth: yes
    body_format: json
    header:
      - Accept: 'application/json'
      - Content-Type: 'application/json'
    body: "{ 'key': '{{ atlassian.jira.project.key }}',
             'name': '{{ atlassian.jira.project.name }}',
             'projectTypeKey': '{{ atlassian.jira.project.type_key }}',
             'projectTemplateKey': '{{ atlassian.jira.project.template_key }}',
             'description': '{{ atlassian.jira.project.description }}',
             'lead': '{{ atlassian.jira.lead }}',
             'assigneeType': 'PROJECT_LEAD',
             'avatarId': 10200,
             'permissionScheme': '{{ PermissionScheme }}',
             'notificationScheme': 10000, 
             'categoryId': '{{ CategoryID }}' 
           }"
    status_code: 201         
  register: result
