---
- import_playbook: ../osp/manage-user-network.yml
  when:
  - hosting_infrastructure == 'openstack'

- import_playbook: ../osp/provision-osp-instance.yml
  when:
  - hosting_infrastructure == 'openstack'

- import_playbook: forward-ip.yml

- name: "Subscribe RHEL based instances" 
  hosts: idm
  roles:
    - rhsm

- import_playbook: dns.yml

- name: 'Install and Configure IdM'
  hosts: idm
  become: True
  roles:
  - role: idm
