---

- name: "Install prereq software"
  package:
    name: 'python2-shade'
    state: present

- name: "Manage Volumes"
  os_volume:
    cloud: "{{ item.cloud | default(osp_default_cloud) | default(omit) }}"
    state: "{{ item.state | default(osp_resource_state) | default('present') }}"
    name: "{{ item.name }}"
    size: "{{ item.size | default(omit) }}"
    display_name: "{{ item.display_name | default(omit) }}"
    display_description: "{{ item.display_description | default(omit) }}"
  register: os_volumes
  with_items:
  - "{{ osp_volumes | default([]) }}"
