---

- name: 'Initialize Facts for VM deployments'
  set_fact:
    virt_install_commands: []
    mounted_iso: {}

- name: 'Gather the list of existing VMs'
  command: virsh list --name
  register: existing_vms
  check_mode: false

- name: 'Compose Command for new VM provisioning'
  include_tasks: 'virt-install.yml'
  when:
    - inventory_hostname == hostvars[instance]['infrahost']
    - hostvars[instance]['libvirt_name'] not in existing_vms.stdout_lines
  with_items:
    - "{{ groups['infra_vms'] }}"
  loop_control:
    loop_var: instance

- name: "Call virt-install to create VMs"
  shell: "{{ item }}"
  with_items: "{{ virt_install_commands }}"
  register: vm_instances
  async: 7200
  poll: 0
  when:
    - virt_install_commands|length > 0

- name: 'Wait for VMs creation to complete'
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: vm_jobs
  until: vm_jobs.finished
  retries: 300
  with_items: "{{ vm_instances.results }}"
  when:
    - virt_install_commands|length > 0

