---
- name: Get attachment data
  uri:
    url: '{{ confluence.source.url }}/rest/api/content/{{ confluence_content_ids.key }}/child/attachment'
    method: GET
    user: '{{ confluence.source.username }}'
    password: '{{ confluence.source.password }}'
    force_basic_auth: yes
    status_code: 200
    return_content: yes
  register: attachments_json

- name: Create temp directory for downloaded attachments
  tempfile:
    state: directory
  register: attachment_tempdir

- include_tasks: download_attachment.yml
  with_items: '{{ attachments_json.json.results }}'
  loop_control:
    loop_var: attachment_data
