---
- name: Download attachment from source
  get_url:
    url: '{{ confluence.space.url }}/wiki{{ attachment_data._links.download }}'
    dest: '{{ attachment_tempdir.path }}/{{ attachment_data.title }}'
    force: yes
    force_basic_auth: yes
    url_username: '{{ confluence.source.username }}'
    url_password: '{{ confluence.source.password }}'
  no_log: true
  delegate_to: 127.0.0.1

- name: Upload attachment to destination
  command: 'curl -u {{ confluence.destination.username }}:{{ confluence.destination.password }} -X POST -H "X-Atlassian-Token: no-check" -F "file=@{{ attachment_tempdir.path }}/{{ attachment_data.title }}" {{ confluence.destination.url }}/wiki/rest/api/content/{{ confluence_content_ids.value.id }}/child/attachment'
  delegate_to: 127.0.0.1
