---

- name: 'Copy the dhcp config file to a temp location for validity checking'
  copy:
    src: '{{ dhcp_config_dir.path }}/{{ dhcp_config_temp_file }}'
    dest: '{{ dhcp_config_temp_loc }}'
  notify: 'cleanup dhcp tmp file'

- name: ' Check the Validity of dhcp.conf file'
  command: 'dhcpd -t -cf {{ dhcp_config_temp_loc }}'
  notify: 'cleanup dhcp tmp file'

- name: 'Copy and activate the dhcp config file'
  copy:
    remote_src: true
    src: '{{ dhcp_config_temp_loc }}'
    dest: '{{ dhcp_config_dest_file }}'
  notify: 'reload dhcp'
