---

- name: "Retrieve template for Identity Provider"
  set_fact:
    id_provider_json: "{{ lookup('template', 'id-providers.json.j2') | to_json }}"

- name: "Requesting Access Token"
  uri:
    url: "{{ rh_sso_protocol }}://{{ rh_sso_host }}:{{ rh_sso_port }}/auth/realms/master/protocol/openid-connect/token"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ rh_sso_admin_user }}"
      password: "{{ rh_sso_admin_pass }}"
      grant_type: "password"
      client_id: "admin-cli"
    validate_certs: "{{ rh_sso_ssl_cert_validation | default(omit) }}"
  register: rh_sso_token

- name: "Create Identity Provider for Red Hat Single Sign-On"
  uri:
    url: "{{ rh_sso_protocol }}://{{ rh_sso_host }}:{{ rh_sso_port }}/auth/admin/realms/{{ id_provider.targetRealm }}/identity-provider/instances"
    method: POST
    body: "{{ id_provider_json }}"
    body_format: json
    status_code: 201, 409
    headers:
      Authorization: "Bearer {{ rh_sso_token.json.access_token }}"
    validate_certs: "{{ rh_sso_ssl_cert_validation | default(omit) }}"
  register: rh_sso_idp_create
