- name: "Request Red Hat SSO REST API Access Token"
  uri:
    url: "https://{{ rh_sso_host }}:{{ rh_sso_port }h/auth/realms/master/protocol/openid-connect/token"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ sso_admin_user }}"
      password: "{{ sso_admin_pass }}"
      grant_type: "password"
      client_id: "admin-cli"
  register: rh_sso_token

- name: "Check if Execution: {{ af_exec.provider }} exists in Authentication Flow: {{ af.name }}"
  set_fact:
    exec_check: "{{ rh_sso_exec.json | json_query(query) }}"
  vars:
    query: "[?providerId=='{{ af_exec.provider }}'].providerId"

- name: "Create New Execution"
  block:
    - debug:
        msg: "Creating new execution"
    - name: "Create New Execution"
      uri:
        url: "https://{{ rh_sso_host }}:{{ rh_sso_port }}/auth/admin/realms/{{ af.realm }}/authentication/flows/{{ af.name }}/executions/execution"
        method: POST
        body:
          provider: "{{ af_exec.provider }}"
        body_format: json
        status_code: 201
        headers:
          Authorization: "Bearer {{ rh_sso_token.json.access_token }}"
      register: exec_out
    - debug:
        msg: "{{ exec_out.location | basename }}"
    - name: "Retrieve Template for Execution Flow"
      set_fact:
        exec_json: "{{ lookup('template', 'auth-flow-exec.json.j2') | to_json }}"
    - debug:
        msg: "{{ exec_json }}"
    - name: "Update Execution Properties"
      uri:
        url: "https://{{ rh_sso_host }}:{{ rh_sso_port }}/auth/admin/realms/{{ af.realm }}/authentication/flows/{{ af.name }}/executions"
        method: PUT
        body: "{{ exec_json }}"
        body_format: json
        status_code: 204
        headers:
          Authorization: "Bearer {{ rh_sso_token.json.access_token }}"
      register: update_out
    - debug:
        msg: "{{ update_out }}"
    - name: "Add config"
      uri:
        url: "https://{{ rh_sso_host }}:{{ rh_sso_port }}/auth/admin/realms/{{ af.realm }}/authentication/executions/{{ (exec_out.location | basename) }}/config"
        method: POST
        body:
          alias: "{{ af_exec.name }}"
        body_format: json
        status_code: 201
        headers:
          Authorization: "Bearer {{ rh_sso_token.json.access_token }}"
  when:
    - exec_check[0] is not defined

- name: "Update Execution"
  debug:
    msg: "Execution type: {{ af_exec.provider }} exists in Authentication Flow: {{ af.name }}"
  when:
    - exec_check[0] is defined
