---

- hosts: ansible-tower
  roles:
  - role: ansible/tower/config-ansible-tower
  - role: ansible/tower/config-ansible-tower-license
  - role: ansible/tower/config-ansible-tower-ldap
  - role: config-packages
  tags:
  - 'never'
  - 'install'

- hosts: tower-management-host
  roles:
  - role: ansible/tower/manage-settings
  - role: ansible/tower/manage-projects
  - role: ansible/tower/manage-credential-types
  - role: ansible/tower/manage-credentials
  - role: ansible/tower/manage-inventories
  - role: ansible/tower/manage-job-templates
  - role: ansible/tower/manage-workflow-templates
  tags:
  - 'always'
