---

- hosts: ansible-tower
  roles:
  - role: ansible/tower/config-ansible-tower
  - role: ansible/tower/config-ansible-tower-license
  - role: ansible/tower/config-ansible-tower-subscription-manifest
  - role: ansible/tower/config-ansible-tower-ldap
  - role: config-packages
  - role: config-pip-packages
  - role: manage-ssh-private-keys
  tags:
  - 'never'
  - 'install'

- hosts: ansible-tower
  roles:
  - role: ansible/tower/config-ansible-tower-ocp
  - role: ansible/tower/config-ansible-tower-subscription-manifest
  - role: ansible/tower/config-ansible-tower-ocp-ssh
  - role: ansible/tower/config-ansible-tower-ocp-ldap-ca
  - role: ansible/tower/config-ansible-tower-ldap
  tags:
  - 'never'
  - 'install-tower-ocp'

- hosts: tower-management-host
  roles:
  - role: ansible/tower/manage-settings
  - role: ansible/tower/manage-credential-types
  - role: ansible/tower/manage-credentials
  - role: ansible/tower/manage-projects
  - role: ansible/tower/manage-inventories
  - role: ansible/tower/manage-job-templates
  - role: ansible/tower/manage-workflow-templates
  - role: ansible/tower/manage-schedules
  tags:
  - 'always'
