---

- name: Ensure the view directory exists
  file:
    path: "{{ dns_zone_temp_config_dir }}/{{ view.name }}"
    state: directory

- name: Set server config facts
  set_fact:
    view_recursion: "{{ view.named.recursion | default(common_recursion) }}"

- name: Prepare the view pre-zones content
  vars:
    view_name: "{{ view.name }}"
    view_recursion: "{{ view_recursion }}"
  template:
    src: view-config-1.j2
    dest: "{{ dns_zone_temp_config_dir }}/{{ view.name }}/0001-{{ view.name }}.cfg"
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0660
  when:
    - view.state|default('present') == 'present'

- name: Initialize flags
  set_fact:
    processed_zones: False

- include_tasks: process-one-zone.yml
  with_items:
    - "{{ view.zones }}"
  loop_control:
    loop_var: "zone"

- block:
  - name: Prepare the view post-zones content
    vars:
      view_forwarders: "{{ view.default_forwarders | default(['127.0.0.1']) }}"
    template:
      src: view-config-2.j2
      dest: "{{ dns_zone_temp_config_dir }}/{{ view.name }}/0003-{{ view.name }}.cfg"
      owner: "{{ bind_user }}"
      group: "{{ bind_group }}"
      mode: 0660

  - name: Assemble the complete view file
    assemble:
      src: "{{ dns_zone_temp_config_dir }}/{{ view.name }}"
      dest: "{{ dns_zone_temp_config_dir }}/view/{{ view_idx }}-{{ view.name }}.cfg"
  when:
    - processed_zones|bool == True
    - view.state|default('present') == 'present'

- name: Remove temporary view if no zones were processed
  file:
    path: "{{ dns_zone_temp_config_dir }}/{{ view.name }}"
    state: absent
  when:
    - processed_zones|bool == False
