---

- name: "Print Host Cert - if requested"
  debug:
    msg: "{{ host_cert.json.result.result.certificate }}"
    verbosity: 2

- name: "Print Host Key - if requested"
  debug:
    msg: "{{ csr_content_output.key }}"
    verbosity: 2

- name: "Print CA cert - if requested"
  debug:
    msg: "{{ ca_cert.json.result.result.certificate }}"
    verbosity: 2
