---

- name: "install epel-release"
  package:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present

- name: "Set installation dir fact"
  set_fact:
    ansible_tower_dir: "{{ ansible_tower_download_url | basename | regex_replace('.tar.gz','') }}"

- name: "Check if installer dir exists"
  stat: 
    path: "{{ ansible_tower_dir }}"
  register: installer_dir

- name: "Download & Unpack Ansible Tower installer"
  shell: curl {{ ansible_tower_download_url }} | tar xzf -
  args:
    warn: False
  when: not installer_dir.stat.exists

- name: "Set up the Ansible Tower inventory"
  template:
    src: inventory.j2
    dest: "{{ ansible_tower_dir }}/inventory"
  register: inventory

- name: "run tower installer"
  shell: ./setup.sh
  args:
    chdir: "{{ ansible_tower_dir }}"

- name: "Wait for Tower to become available before proceeding (30 sec max)"
  uri:
    url: https://localhost/api/v1/config/
    method: GET
    user: admin
    password: "{{ tower_admin_password }}"
    validate_certs: no
  register: status_output
  until: status_output.status == 200
  retries: 6
  delay: 5

- name: "Add Tower license"
  uri: 
    url: https://localhost/api/v1/config/
    method: POST
    body: '{{ lookup("file", tower_license_file) | from_json | combine({"eula_accepted":"true"}) | to_json }}'
    body_format: 'json'
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    user: admin
    password: "{{ tower_admin_password }}" 
    validate_certs: no

- name: "Download and Install the 'oc' client for OpenShift interactions"
  shell: curl {{ oc_client_download_url }} | tar -C /bin/ -xzf -
  args:
    warn: False

- name: "Copy custom Tower SSL certificate and Key"
  block:
    - copy:
        src: "{{ tower_custom_ssl_certificate.cert }}"
        dest: /etc/tower/tower.cert

    - copy:
        src: "{{ tower_custom_ssl_certificate.key }}"
        dest: /etc/tower/tower.key
  when: tower_custom_ssl_certificate is defined  
