---

- name: Check for Python shade module
  python_requirements_info:
    dependencies:
      - shade

- name: Manage OpenStack instance
  os_server:
    cloud: "{{ item.cloud | default(osp_default_cloud) | default(omit) }}"
    state: "{{ item.state | default(osp_resource_state) | default('present') }}"
    name: "{{ item.name }}"
    image: "{{ item.image | default(omit) }}"
    key_name: "{{ item.key_name | default(omit) }}"
    timeout: 200
    flavor: "{{ item.flavor | default(omit) }}"
    network: "{{ item.network | default(omit) }}"
    security_groups: "{{ item.security_groups | default(omit) }}"
    auto_ip: "{{ item.auto_ip | default(True) }}"
    delete_fip: "{{ item.delete_fip | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    meta: "{{ item.meta | default(omit) }}"
    userdata: "{{ item.userdata | default(omit) }}"
  register: os_servers
  with_items:
    - "{{ osp_instances | default([]) }}"
