---

- name: "Detect the physical device based on iSCSI lun"
  shell: 'lsscsi | sed -ne "s/.*:{{ disk.lun }}].*{{ iscsi_brand }}.*\(\/dev\/.*\)$/\1/p"'
  register: lsscsi

- name: "Detect the multipath device id based on physical device"
  shell: 'multipath -l {{ lsscsi.stdout_lines[0] }} | sed -ne "s/\([^ ]*\).*{{ iscsi_brand }}.*/\1/p"'
  register: multipath_id

- name: "Setup and create PV & VG"
  lvg:
    vg: "{{ disk.vg }}"
    pvs: "/dev/mapper/{{ multipath_id.stdout }}"
    force: yes

- name: "Setup LV"
  lvol:
    vg: "{{ disk.vg }}"
    lv: "{{ disk.lv }}"
    force: yes
    size: "100%VG"
  when:
    - disk.lv is defined
    - disk.lv|trim != ''

- name: "Create file system on share"
  filesystem:
    fstype: xfs
    dev: "/dev/mapper/{{ disk.vg }}-{{ disk.lv }}"
  when:
    - disk.lv is defined
    - disk.lv|trim != ''

- name: "Ensure the base dir for the mount point exists"
  file:
    path: "{{ disk.mount_path|dirname }}"
    state: directory
  when:
    - disk.mount_path is defined
    - disk.mount_path|trim != ''

- name: "Mount the share"
  mount:
    src: "/dev/mapper/{{ disk.vg }}-{{ disk.lv }}"
    path: "{{ disk.mount_path }}"
    opts: _netdev
    fstype: xfs
    state: mounted
  when:
    - disk.mount_path is defined
    - disk.mount_path|trim != ''

