---

- name: 'Copy the HAproxy config file to a temp location for validity checking'
  copy:
    src: '{{ haproxy_temp_file }}'
    dest: '{{ temp_new_file }}'

- name: 'Check the validity'
  command: 'haproxy -c -f {{ temp_new_file }}'
  notify: 'remove tmp new file'

- name: 'Copy and activate the HAproxy config file'
  copy:
    src: '{{ haproxy_temp_file }}'
    dest: '/etc/haproxy/haproxy.cfg'
    backup: 'yes'
  notify: 'reload haproxy'

- name: 'Clean-up the temp file'
  file:
    path: "{{ haproxy_temp_file }}"
    state: absent
  when:
  - (clean_up_temp|default('yes'))|lower == 'yes'
  delegate_to: localhost
  run_once: True
