---

- name: 'Subscribe the hosts to RHSM'
  hosts: infra_hosts
  vars:
    rhsm_username: "{{ hostvars['localhost'].rhsm_username }}"
    rhsm_password: "{{ hostvars['localhost'].rhsm_password }}"
  roles:
  - role: rhsm
  tags:
  - configure_rhsm

- name: 'Configure networking on the infrastructure hosts'
  hosts: infra_hosts
  roles:
  - role: config-bonding
  - role: config-vlans
  tags: 
  - configure_infra_hosts_networking
  
- name: 'Configure libvirt on the infrastructure hosts'
  hosts: infra_hosts
  roles:
  - role: config-libvirt
  tags: 
  - configure_infra_hosts_libvirt
  
- name: 'Configure the software source to ensure it is available for use'
  hosts: infra_hosts
  roles:
  - role: config-software-src
  tags: 
  - configure_software_src

- name: 'Make sure the host is running the latest'
  hosts: infra_hosts
  roles:
  - role: update-host
  tags: 
  - update_host

- name: 'Setup iSCSI and MultiPathing - if applicable'
  hosts: infra_hosts
  roles:
  - role: config-iscsi-client
  tags:
  - configure_iscsi_client

