---

# Make sure to run the "prep.yml" playbook before running this playbook

- hosts: rhsm_hosts
  vars:
    rhsm_username: "{{ hostvars['localhost'].rhsm_username | default(omit) }}"
    rhsm_password: "{{ hostvars['localhost'].rhsm_password | default(omit) }}"
  roles: 
  - role: rhsm
    no_log: True
  tags:
  - configure_rhsm


